# Documentation References:
# - Creating a Composite Action: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# - Metadata Syntax for Inputs: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
# - Runs for Composite Actions: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-run-steps-actions
# - Composer CLI Documentation: https://getcomposer.org/doc/03-cli.md#composer-cache-dir
# - Other Implementations: https://github.com/ergebnis/.github/blob/main/actions

name: ðŸ—‚ Get composer cache directory
description: Determines the composer cache directory and exports it as COMPOSER_CACHE_DIR environment variable

inputs:
  working-directory:
    default: .
    description: Which directory to use as working directory
    required: true

runs:
  using: composite

  steps:
    - name: ðŸ” Get composer cache directory
      run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir --working-dir=${{ inputs.working-directory }})" >> $GITHUB_ENV
      shell: bash
