---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
      - id: commitizen
        stages:
          - commit-msg

  - repo: https://github.com/mpalmer/action-validator
    rev: v0.7.1
    hooks:
      - id: action-validator

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yaml]

  - repo: local
    hooks:
      - id: markdownlint
        name: markdownlint-cli2
        description: Run markdownlint-cli2 on your Markdown files using the docker image
        language: docker_image
        types: [markdown]
        entry: davidanson/markdownlint-cli2-rules:latest

...
